/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import DTO.ClienteDTO;
import DTO.ExpedienteDTO;
import controles.CtrlClientes;
import controles.ctrlExpedientes;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jvale
 */
public class FrmExpedientes extends javax.swing.JFrame {

    ctrlExpedientes ctrl;
    CtrlClientes ctrlClientes;

    /**
     * Creates new form FrmExpedientes
     */
    public FrmExpedientes() {
        initComponents();
        ajustesPantalla();
        panel.setBackground(Color.WHITE);
        tablaExpedientes.setRowHeight(25);
        tablaExpedientes.setBackground(Color.WHITE);

        // Personalizar colores de los encabezados
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        Color colorTurquesa = new Color(196, 253, 239);
        headerRenderer.setBackground(colorTurquesa);
        headerRenderer.setForeground(Color.black);
        Font font = tablaExpedientes.getTableHeader().getFont().deriveFont(Font.BOLD);
        headerRenderer.setFont(font);
        tablaExpedientes.getTableHeader().setDefaultRenderer(headerRenderer);
        tablaExpedientes.setBackground(Color.WHITE);
        llenarTabla();
    }
    
    
     private void ajustesPantalla() {
        // Establecer las dimensiones de la ventana
        int width = 1050;
        int height = 575;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        setBounds(x, y, width, height);

        // Evitar que se pueda redimensionar la ventana
        setResizable(false);
    }
    
    private void llenarTabla(){
        ctrl = new ctrlExpedientes();
        List<ExpedienteDTO> lista = new LinkedList<>();
        lista.addAll(ctrl.consultarExpedientes());
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaExpedientes.getModel();
        modeloTabla.setRowCount(0);
        lista.forEach(expediente
                -> {
            Object[] fila = new Object[2];
            fila[0] = expediente.getNombreCliente();
            fila[1]= expediente.getTelefonoCliente();
            modeloTabla.addRow(fila);
        });
    }
    private void buscarCliente(){
        ctrl = new ctrlExpedientes();
        List<ExpedienteDTO> dto = ctrl.consultarExpedientesCliente(txtClienteBuscar.getText());
        if(dto!=null){
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaExpedientes.getModel();
            modeloTabla.setRowCount(0);
            dto.forEach(expediente
                -> {
            Object[] fila = new Object[2];
            fila[0] = expediente.getNombreCliente();
            fila[1] = expediente.getTelefonoCliente();
            modeloTabla.addRow(fila);
        });
        }else{
            JOptionPane.showMessageDialog(this, "No hay expediente de ese cliente","Error",JOptionPane.ERROR_MESSAGE);       
            
        }
        
    }
    private String clienteSeleccionado(){
        int indice = this.tablaExpedientes.getSelectedRow();
        if (indice != -1) {
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tablaExpedientes.getModel();
            int indiceColumnaId = 1;
            String clientes = modeloTabla.getValueAt(indice, indiceColumnaId).toString();
            return clientes;
        } else {
            return null;
        }
    }
    private void mostrarDetalles(){
        ctrlClientes = new CtrlClientes();
        ExpedienteDTO ex = ctrl.consultarExpediente(clienteSeleccionado());
        
        String pato = ex.getAntecedentesPatologicos();
        String perso = ex.getAntecedentesPersonales();
        String piel = ex.getDiagnosticoPiel();
        String uso = ex.getCosmeticosUso();
        ClienteDTO cliente = ctrlClientes.consultarCliente(clienteSeleccionado());
        
        
        FrmDatosExpedientes frm = new FrmDatosExpedientes();
        frm.clientesComboBoxModel.removeAllElements();
        frm.setearDatos(pato, perso, uso, piel, cliente);
        frm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtClienteBuscar = new javax.swing.JTextField();
        btnBuscarExpedienteCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaExpedientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Expedientes");

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setText("Cliente:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 52, 52, -1));

        txtClienteBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteBuscarActionPerformed(evt);
            }
        });
        panel.add(txtClienteBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 47, 850, -1));

        btnBuscarExpedienteCliente.setBackground(new java.awt.Color(232, 244, 255));
        btnBuscarExpedienteCliente.setText("Buscar");
        btnBuscarExpedienteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarExpedienteClienteActionPerformed(evt);
            }
        });
        panel.add(btnBuscarExpedienteCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 70, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPane1MousePressed(evt);
            }
        });

        tablaExpedientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre cliente", "Teléfono cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaExpedientes.getTableHeader().setResizingAllowed(false);
        tablaExpedientes.getTableHeader().setReorderingAllowed(false);
        tablaExpedientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaExpedientesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaExpedientes);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 88, 1000, 390));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Expedientes");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Menú principal");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarExpedienteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarExpedienteClienteActionPerformed
        if(txtClienteBuscar.getText().isEmpty()){
            llenarTabla();
        }else{
            buscarCliente();
        }
    }//GEN-LAST:event_btnBuscarExpedienteClienteActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed
        dispose();
    }//GEN-LAST:event_jMenu1MousePressed

    private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed

    }//GEN-LAST:event_jScrollPane1MousePressed

    private void tablaExpedientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaExpedientesMousePressed
        mostrarDetalles();
        dispose();
    }//GEN-LAST:event_tablaExpedientesMousePressed

    private void txtClienteBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmExpedientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmExpedientes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarExpedienteCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tablaExpedientes;
    private javax.swing.JTextField txtClienteBuscar;
    // End of variables declaration//GEN-END:variables
}
