package frm;

import java.awt.Color;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dianey Elisa Velasquez Busani - 00000228270
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        menuAgregarExpediente.setOpaque(true);
        menuAgregarExpediente.setBackground(Color.decode("#FFC5C5"));
        menuConsultarExpedientes.setOpaque(true);
        menuConsultarExpedientes.setBackground(Color.decode("#FFC5C5"));
        Menu.setOpaque(true);
        Menu.setBackground(Color.decode("#C5FFF3"));
        menuExpediente.setOpaque(true);
        menuExpediente.setBackground(Color.decode("#C5FFF3"));
        UIManager.put("MenuBar.background", Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        menuExpediente = new javax.swing.JMenu();
        menuAgregarExpediente = new javax.swing.JMenuItem();
        menuConsultarExpedientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galiz Estudio");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuBar.setBackground(new java.awt.Color(255, 216, 206));

        Menu.setBackground(new java.awt.Color(204, 255, 255));
        Menu.setBorder(null);
        Menu.setText("Menu");

        menuExpediente.setBackground(new java.awt.Color(204, 255, 255));
        menuExpediente.setText("Expedientes");

        menuAgregarExpediente.setBackground(new java.awt.Color(204, 255, 255));
        menuAgregarExpediente.setText("Agregar expediente");
        menuAgregarExpediente.setBorder(null);
        menuAgregarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarExpedienteActionPerformed(evt);
            }
        });
        menuExpediente.add(menuAgregarExpediente);

        menuConsultarExpedientes.setBackground(new java.awt.Color(204, 255, 255));
        menuConsultarExpedientes.setText("Consultar Expedientes");
        menuConsultarExpedientes.setBorder(null);
        menuConsultarExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarExpedientesActionPerformed(evt);
            }
        });
        menuExpediente.add(menuConsultarExpedientes);

        Menu.add(menuExpediente);

        menuBar.add(Menu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarExpedienteActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDatosExpedientes().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuAgregarExpedienteActionPerformed

    private void menuConsultarExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarExpedientesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmExpedientes().setVisible(true);
            }
        });
    }//GEN-LAST:event_menuConsultarExpedientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAgregarExpediente;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuConsultarExpedientes;
    private javax.swing.JMenu menuExpediente;
    // End of variables declaration//GEN-END:variables
}
